export const QUERY_KEYS = {
  PARTIES: ["parties"] as const,
  PRODUCTS: ["products"] as const,
  OPERATIONS: ["operations"] as const,
  GST: ["gst"] as const,
  KARIGARS: ["karigars"] as const,
  PURCHASE_ORDERS: ["purchase-orders"] as const,
  PURCHASE_BILLS: ["purchase-bills"] as const,
  STOCK: ["stock"] as const,
  ISSUES: ["issues"] as const,
  WASTAGE: ["wastage"] as const,
  PRODUCTION: ["production"] as const,
  BUNDLES: ["bundles"] as const,
  BOXES: ["boxes"] as const,
  CONTAINERS: ["containers"] as const,
  SALES_BILLS: ["sales-bills"] as const,
  SALES_NOTES: ["sales-notes"] as const,
  KARIGAR_PAYMENTS: ["karigar-payments"] as const,
  SUPPLIER_PAYMENTS: ["supplier-payments"] as const,
  VOUCHERS: ["vouchers"] as const,
  ACCOUNT_STATEMENT: ["account-statement"] as const,
  TEAM_MEMBERS: ["team-members"] as const,
  NOTIFICATIONS: ["notifications"] as const,
  SEARCH: ["search"] as const,
} as const;
